### PR TITLE
Adding tests plus travis build.

### PR DESCRIPTION
**Pull request by mithro**

### CODE REVIEW

**Comment by mithro** [comment]
@jleclanche can you take a look at this and see what you think?

**Comment by mithro** [comment]
Travis results are at https://travis-ci.org/mithro/q/builds/66147587

**Comment by mithro** [comment]
@zestyping Can you enable the Travis-CI webhook for this repository? Go to https://travis-ci.org/profile/zestyping and click the slider next to zestyping/q

**Comment by jleclanche** [comment]
Looks great. lgtm

**Comment by jleclanche** [comment]
Make sure to take a look at #19 when you can, please :)

**Pull request merged**
