### PR TITLE
Adding tests for tracing and fixing it when using decorators.

### LINKED ISSUE #10: @q vs @q.t
In 2.3, using q as a decorator for tracing a function seems to be broken.  @q.t still works.

$ cat test.py
import q

@q
def log(msg='default'):
    return msg

@q.t
def sudo_log(msg='default'):
    return msg

log('me a message')
sudo_log('me a message')

$ cat /tmp/q

 0.0s <module>: <function log>
 0.0s sudo_log('me a message')
 0.0s -> 'me a message'

Not sure if this is something simple to fix in the code or if the README.md should just be changed to say that @q.t should be used.

### PR DESCRIPTION
**Pull request by mithro**
Fixes #10.

Originally based on code in https://github.com/mithro/q/pull/1 and https://github.com/zestyping/q/pull/11

### CODE REVIEW

**Comment by mithro** [comment]
This change be merged after https://github.com/zestyping/q/pull/25 which should leave the last 3 commits.
Travis output at https://travis-ci.org/mithro/q/builds/66192445

@abadger - Would love you to check that I haven't broken your code.

**Comment by mithro** [comment]
@jleclanche - Can you take a look at this?
Latest travis-ci build at https://travis-ci.org/mithro/q/builds/66480023

**Comment by jleclanche** [comment]
This is out of my depth :)

**Comment by mithro** [comment]
Well, I think I'm going to merge this as the tests seem to indicate it works and fixes the bug.

**Comment by jleclanche** [comment]
@mithro can you make sure a new release is out once all those issues are fixed?

**Comment by mithro** [comment]
I'll look at doing one on the weekend or next week. Please do keep
pestering me otherwise it is likely to drop off my TODO list.

**Comment by mithro** [comment]
q version 2.6 has been tagged and released onto PyPi.

Can people please test that everything is good? @jleclanche

**Comment by jleclanche** [comment]
Thanks, will be testing it over time. Looks good so far.

**Pull request merged**
