### PR TITLE
Adding test for more functionality and working around a Python 3.4 bug.

### LINKED ISSUE #19: In master with python 3, accessing self attributes messes with the argument order
Eg:

```
 0.3s getProperty: self, self.=<Weapon ('Fiery War Axe')>,
      data=<fireplace.xmlcard.XMLCard object>, prop='atk', ret, self.=0,
      slots=[]
```

This was from a call to self=, self.data=, prop=, ret=, self.slots=. The names are all mixed up every call to self.

### PR DESCRIPTION
**Pull request by mithro**
See the bug at https://bugs.python.org/issue21295
The bug doesn't effect Python versions newer than 3.4 and a fix should be landed in Python 3.4.3 and in Python 3.5 onwards.
    
Fixes #19.

### CODE REVIEW

**Comment by mithro** [comment]
@jleclanche Can you please take look at this?

**Comment by mithro** [comment]
Build at https://travis-ci.org/mithro/q/builds/66175216

**Comment by mithro** [comment]
@jleclanche Did this fix the issue for you?

**Comment by jleclanche** [comment]
Sure. Please squash all the commits together though before you merge, no need to pollute the log :)

**Comment by mithro** [comment]
@jleclanche - I don't think it's worth squashing in this case.

**Comment by jleclanche** [comment]
Doesn't take long.. :)

**Pull request merged**
